### PR TITLE
implemented feature to get historic price trend of a stock over certain fixed time intervals.

### PR DESCRIPTION
**Pull request by paul-antony**
Implemented feature to get historic price trend of a stock over certain fixed time intervals. This feature collects historic data like price and volume of the stalk over certain pre-defined period. 

The pre-defined period are ```1D```, ```5D```, ```1M```, ```3M```, ```6M```, ```12M```.

This data can be used to visualise the latest trends in the stock.

### CODE REVIEW

**Comment by sdabhi23** [comment]
Hey @paul-antony this looks awesome! Can you also help out with writing test cases for this?

**Comment by paul-antony** [comment]
Sure, I will try to write some test cases for it.

**Comment by paul-antony** [comment]
added some test and some slight modification to the code.

Modification 
converted some of the output from string to int,float.
added an assert to check if its a valid stock

**Comment by paul-antony** [comment]
@sdabhi23 is there anything else needed to be added to the code

**Comment by sdabhi23** [comment]
Hey @paul-antony, I was busy last couple of weeks and so haven't yet properly reviewed the changes. Am planning to review and merge the changes next weekend

**Comment by sdabhi23** [comment]
@paul-antony have updated some parts of the functions and test cases. The reasoning for the same is as below:

* Removed dependency on verifyScripCodes: The flag to download the scrip codes file is set to `False` by default. Hence, the calls to `getPeriodTrend` can fail if the user initializes the object in default manner. This can lead to unwanted confusion.
* Dropped support for '1D' and '5D' time periods: For 1D and 5D, the vol and price values are not EOD, while for the rest of the time periods the values are of `00:00:00` on the given date. Combining them in a single method can lead to unwanted confusion.
* Improved test cases: Please refer to the code to understand the changes

**Comment by sdabhi23** [comment]
Contributes towards #3

**Pull request merged**
