### PR TITLE
Imeplemented regex to extract company names & symbol codes from quandl url

### PR DESCRIPTION
**Pull request by HasanFaraaz**

### CODE REVIEW

**Comment by HasanFaraaz** [comment]
Fixed a bug in regex extraction

**Comment by HasanFaraaz** [comment]
Reopened PR, after self reviewing code. Test cases may fail, but feature implementation is correct.

**Comment by sdabhi23** [comment]
@HasanFaraaz thanks a lot for the PR. The tests are failing as you have not stripped **" EOD Prices"** from the company name. It has to be removed, without that this PR won't be merged.

It would be great if you could implement a similar mechanism using regex for indices as well. I am ready to wait till you complete it, as I would like to keep all the logic in sync across this library! 😄

**Comment by sdabhi23** [comment]
@HasanFaraaz are you planning to update this PR?

**Comment by sdabhi23** [comment]
Closed due to inactivity and failing tests

**Pull request closed without merging**
